manytree:
  url:
    jwtKey: http://localhost:8080/.well-known/jwks.json
    endpoint: http://localhost:8080/endpoints/proxy
    report: http://localhost:8080/reports/proxy
    clients: http://localhost:8080/clients/proxy
  domain-name:
  instance-id: 0
mt:
  url:
    support:
      mq:
server:
  port: 8111
spring:
  application:
    name: 0C8AZYTQ5W5C
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 15s
  loadbalancer:
    ribbon:
      enabled: false
  redis:
    port:
    database: 0
    host:
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
ribbon:
  ReadTimeout: 15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 35000
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone:
  instance:
    preferIpAddress: true
    ip-address:
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 10
