mt:
  rabbitmq:
    url:
  redis:
    url:
    client-name: mt-proxy
  misc:
    domain:
    instance-id:
    url:
      access:
server:
  port: 8111
spring:
  application:
    name: 0C8AZYTQ5W5C
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 15s