mt:
  rabbitmq:
    url:
  redis:
    url:
    client-name: mt-proxy
  misc:
    domain:
    instance-id:
    url:
      access:
server:
  port: 8111
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 15s
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true