manytree:
  mt-access:
    appId: 0C8AZTODP4HT
  url:
    endpoint: endpoints/proxy
    clients: clients/proxy
  domain-name: duoshu.org
mt:
  url:
    support:
      mq:
server:
  port: 8111
spring:
  application:
    name: 0C8AZYTQ5W5C
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 15s
  loadbalancer:
    ribbon:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: .well-known/jwks.json
  redis:
    port:
    database: 0
    host:
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
ribbon:
  ReadTimeout: 15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 35000
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
    com:
      netflix: INFO
eureka:
  client:
    serviceUrl:
      defaultZone:
    registryFetchIntervalSeconds: 1
  instance:
    preferIpAddress: true
    ip-address:
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 10
